import type { Metadata } from "next";
import "@/app/styles/globals.css";
import { geistSans, geistMono } from "@/app/styles/fonts";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import {Provider} from "@/app/utils/Provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${fredoka.className} antialiased`}> */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <div className="relative max-w-full overflow-hidden">
            <Navbar />
            <main className="bg-secondary-200">
              {children}
            </main>
                  {/* <BackToTop /> */}
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
